services:

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/certs/:/etc/nginx/ssl
      - ./nginx/conf/:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

  db:
    restart: "no"
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  backend:
    restart: "no"
    ports:
      - "8888:8888"
    volumes:
      - ./backend/:/app
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command: /start-reload.sh

  frontend:
    restart: "no"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://${DOMAIN?Variable not set}
        - NODE_ENV=development

networks:
  npm-nw:
    # For local dev, don't expect an external Traefik network
    external: false
