"""Modified CnvMessageModel

Revision ID: 2bcdf4d781c2
Revises: c26ccbfa7b4f
Create Date: 2024-05-10 13:28:54.747383

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2bcdf4d781c2'
down_revision = 'c26ccbfa7b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cnvmessage', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cnvmessage', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cnvmessage', 'content')
    op.drop_column('cnvmessage', 'role')
    # ### end Alembic commands ###
