"""modified model

Revision ID: c26ccbfa7b4f
Revises: 28bf59d877db
Create Date: 2024-05-09 13:43:36.038685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c26ccbfa7b4f'
down_revision = '28bf59d877db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
