"""Modified CnvMessageModel

Revision ID: c4cf4e1f915b
Revises: 5a032a15d5a5
Create Date: 2024-05-10 18:41:43.024395

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4cf4e1f915b'
down_revision = '5a032a15d5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('modified_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'modified_at')
    # ### end Alembic commands ###
