"""Modified CnvMessageModel

Revision ID: c63af2416866
Revises: c4cf4e1f915b
Create Date: 2024-05-10 20:06:56.585064

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c63af2416866'
down_revision = 'c4cf4e1f915b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
