name: Deploy to Staging

on:
  workflow_run:
    workflows: [ Test ]
    types: [ completed ]

jobs:
  build:
    if: ${{ GITHUB.REF.NAME == 'master' }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: staging
      DOMAIN: ${{ vars.DOMAIN_STAGING }}
      STACK_NAME: ${{ vars.STACK_NAME_STAGING }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ vars.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=COMMIT_SHA::$(git rev-parse --short HEAD)"

      - name: Build Docker images for stg
        run: docker-compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} build

      - name: Push Docker images for stg
        run: docker-compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} push

  deploy:
    if: ${{ GITHUB.REF.NAME == 'master' }}
    runs-on:
      - self-hosted
      - staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} down
      - run: docker-compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} up -d
