name: Publish docker images

on:
  workflow_run:
    workflows: [ Test ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=COMMIT_SHA::$(git rev-parse --short HEAD)"

      - name: Build and push Docker images
        run: |
          docker-compose build --build-arg COMMIT_SHA=${{ steps.commit_sha.outputs.COMMIT_SHA }}
          docker-compose push